var dir_b00278d2a123a175db165a8d978eb3df =
[
    [ "double_insert_segment.cpp", "double__insert__segment_8cpp_source.html", null ],
    [ "double_insert_segment.hpp", "double__insert__segment_8hpp_source.html", null ],
    [ "double_remove_segment.cpp", "double__remove__segment_8cpp_source.html", null ],
    [ "double_remove_segment.hpp", "double__remove__segment_8hpp_source.html", null ],
    [ "insert_segment.cpp", "insert__segment_8cpp_source.html", null ],
    [ "insert_segment.hpp", "insert__segment_8hpp_source.html", null ],
    [ "insert_spin_segment.cpp", "insert__spin__segment_8cpp_source.html", null ],
    [ "insert_spin_segment.hpp", "insert__spin__segment_8hpp_source.html", null ],
    [ "move_segment.cpp", "move__segment_8cpp_source.html", null ],
    [ "move_segment.hpp", "move__segment_8hpp_source.html", null ],
    [ "regroup_segment.cpp", "regroup__segment_8cpp_source.html", null ],
    [ "regroup_segment.hpp", "regroup__segment_8hpp_source.html", null ],
    [ "regroup_spin_segment.cpp", "regroup__spin__segment_8cpp_source.html", null ],
    [ "regroup_spin_segment.hpp", "regroup__spin__segment_8hpp_source.html", null ],
    [ "remove_segment.cpp", "remove__segment_8cpp_source.html", null ],
    [ "remove_segment.hpp", "remove__segment_8hpp_source.html", null ],
    [ "remove_spin_segment.cpp", "remove__spin__segment_8cpp_source.html", null ],
    [ "remove_spin_segment.hpp", "remove__spin__segment_8hpp_source.html", null ],
    [ "split_segment.cpp", "split__segment_8cpp_source.html", null ],
    [ "split_segment.hpp", "split__segment_8hpp_source.html", null ],
    [ "split_spin_segment.cpp", "split__spin__segment_8cpp_source.html", null ],
    [ "split_spin_segment.hpp", "split__spin__segment_8hpp_source.html", null ],
    [ "swap_spin_lines.cpp", "swap__spin__lines_8cpp_source.html", null ],
    [ "swap_spin_lines.hpp", "swap__spin__lines_8hpp_source.html", null ]
];