triqs::det_manip::det_manip< FunctionType > Class Template Reference
triqs::det_manip::det_manip< FunctionType > Class Template Reference
Standard matrix/det manipulations used in several QMC.
#include <det_manip.hpp>
Classes
struct work_data_type1
struct work_data_type2
Public Types
enum RollDirection {
None, Up, Down, Left,
Right
}
typedef f_tr::template
decay_arg< 0 >::type xy_type
typedef f_tr::result_type value_type
typedef arrays::vector
< value_type > vector_type
typedef arrays::matrix
< value_type > matrix_type
typedef arrays::matrix_view
< value_type > matrix_view_type
Public Member Functions
static_assert (std::is_floating_point< value_type >::value||triqs::is_complex< value_type >::value,"det_manip : the function must return a floating number or a complex number")
void reserve (size_t new_size)
det_manip (FunctionType F, size_t init_size)
Constructor.
template<typename ArgumentContainer1 , typename ArgumentContainer2 >
det_manip (FunctionType F, ArgumentContainer1 const &X, ArgumentContainer2 const &Y)
Constructor.
det_manip (det_manip const &)
det_manip (det_manip &&rhs) noexcept
det_manip & operator= (const det_manip &)
det_manip & operator= (det_manip &&rhs) noexcept
void clear ()
Put to size 0 : like a vector.
size_t size () const
Current size of the matrix.
xy_type const & get_x (size_t i) const
Returns the i-th values of x.
xy_type const & get_y (size_t j) const
Returns the j-th values of y.
value_type determinant () const
value_type inverse_matrix (size_t i, size_t j) const
matrix_view_type inverse_matrix () const
Returns the inverse matrix. Warning : this is slow, since it create a new copy, and reorder the lines/cols.
matrix_view_type matrix () const
Rebuild the matrix. Warning : this is slow, since it create a new matrix and re-evaluate the function.
value_type try_insert (size_t i, size_t j, xy_type const &x, xy_type const &y)
template<typename Fx , typename Fy >
value_type try_insert_from_function (size_t i, size_t j, Fx fx, Fy fy, value_type const ksi)
value_type try_insert2 (size_t i0, size_t i1, size_t j0, size_t j1, xy_type const &x0, xy_type const &x1, xy_type const &y0, xy_type const &y1)
value_type try_remove (size_t i, size_t j)
value_type try_remove2 (size_t i0, size_t i1, size_t j0, size_t j1)
value_type try_change_col (size_t j, xy_type const &y)
value_type try_change_row (size_t i, xy_type const &x)
void complete_operation ()
int roll_matrix (RollDirection roll)
Protected Types
typedef std::ptrdiff_t int_type
typedef arrays::range range
Protected Attributes
FunctionType f
value_type det
size_t Nmax
size_t N
size_t last_try
std::vector< size_t > row_num
std::vector< size_t > col_num
std::vector< xy_type > x_values
std::vector< xy_type > y_values
int sign
matrix_type mat_inv
long long n_opts
long long n_opts_max_before_check
Friends
class boost::serialization::access
void h5_write (h5::group fg, std::string subgroup_name, det_manip const &g)
Write into HDF5.
void h5_read (h5::group fg, std::string subgroup_name, det_manip &g)
Read from HDF5.
void swap (det_manip &lhs, det_manip &rhs) noexcept
template<typename LambdaType >
void foreach (det_manip const &d, LambdaType const &f)
Detailed Description
template<typename FunctionType>
class triqs::det_manip::det_manip< FunctionType >
Standard matrix/det manipulations used in several QMC.
Constructor & Destructor Documentation
template<typename FunctionType > triqs::det_manip::det_manip< FunctionType >::det_manip (FunctionType F, size_t init_size) [inline]
Constructor.
Parameters:
F The function (NB : a copy is made of the F object in this class).
init_size The maximum size of the matrix before a resize (like reserve in std::vector). Like std::vector, resize is automatic (by a factor 2) but can yield a performance penalty if it happens too often.
References triqs::det_manip::det_manip< FunctionType >::reserve().
template<typename FunctionType > template<typename ArgumentContainer1 , typename ArgumentContainer2 > triqs::det_manip::det_manip< FunctionType >::det_manip (FunctionType F, ArgumentContainer1 const & X, ArgumentContainer2 const & Y) [inline]
Constructor.
Parameters:
F The function (NB : a copy is made of the F object in this class).
Template Parameters:
ArgumentContainer
Parameters:
X,Y : container for X,Y.
References triqs::det_manip::det_manip< FunctionType >::determinant(), and triqs::det_manip::det_manip< FunctionType >::reserve().
Member Function Documentation
template<typename FunctionType > void triqs::det_manip::det_manip< FunctionType >::complete_operation () [inline]
Finish the move of the last try_xxx called. Throws if no try_xxx has been done or if the last operation was complete_operation.
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::determinant () const [inline]
det M of the current state of the matrix.
Referenced by triqs::det_manip::det_manip< FunctionType >::det_manip().
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::inverse_matrix (size_t i, size_t j) const [inline]
Returns M^{-1}(i,j)
template<typename FunctionType > void triqs::det_manip::det_manip< FunctionType >::reserve (size_t new_size) [inline]
Like for std::vector, reserve memory for a bigger size. Preserves only the matrix, not the temporary working vectors/matrices, so do NOT use it between a try_XXX and acomplete_operation
Referenced by triqs::det_manip::det_manip< FunctionType >::det_manip(), triqs::det_manip::det_manip< FunctionType >::try_insert(), and triqs::det_manip::det_manip< FunctionType >::try_insert2().
template<typename FunctionType > int triqs::det_manip::det_manip< FunctionType >::roll_matrix (RollDirection roll) [inline]
"Cyclic Rolling" of the determinant.
Right : Move the Nth col to the first col cyclically. Left : Move the first col to the Nth, cyclically. Up : Move the first row to the Nth, cyclically. Down : Move the Nth row to the first row cyclically.
Returns -1 is the roll changes the sign of the det, 1 otherwise NB : this routine is not a try_xxx : it DOES make the modification and does not need to be completed... WHY is it like this ???? : try_roll : return det +1/-1.
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::try_change_col (size_t j, xy_type const & y) [inline]
Consider the change the column j and the corresponding y.
Returns the ratio of det Minv_new / det Minv. This routine does NOT make any modification. It has to be completed with complete_operation().
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::try_change_row (size_t i, xy_type const & x) [inline]
Consider the change the row i and the corresponding x.
Returns the ratio of det Minv_new / det Minv. This routine does NOT make any modification. It has to be completed with complete_operation().
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::try_insert (size_t i, size_t j, xy_type const & x, xy_type const & y) [inline]
Insert operation at colum j0 and row i0.
The operation consists in adding :
* a column f(x_i, y_{j0}) * and a row f(x_{i0}, x_j)
The new colum/row will be at col j0, row i0.
0 <= i0,j0 <= N, where N is the current size of the matrix. The current column j0 (resp. row i0) will become column j0+1 (resp. row i0+1). Inserting at N simply add the new col at the end.
Returns the ratio of det Minv_new / det Minv.
This routine does NOT make any modification. It has to be completed with complete_operation().
References triqs::det_manip::det_manip< FunctionType >::reserve().
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::try_insert2 (size_t i0, size_t i1, size_t j0, size_t j1, xy_type const & x0, xy_type const & x1, xy_type const & y0, xy_type const & y1) [inline]
Double Insert operation at colum j0,j1 and row i0,i1.
The operation consists in adding : * a column f(x_i, y_{j0}) * and a row f(x_{i0}, x_j) The new colum/row will be at col j0, row i0.
0 <= i0,i1,j0,j1 <= N+1, where N is the current size of the matrix. Returns the ratio of det Minv_new / det Minv. This routine does NOT make any modification. It has to be completed with complete_operation().
References triqs::det_manip::det_manip< FunctionType >::reserve().
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::try_remove (size_t i, size_t j) [inline]
Consider the removal the colj0 and row i0 from the matrix.
Returns the ratio of det Minv_new / det Minv. This routine does NOT make any modification. It has to be completed with complete_operation().
template<typename FunctionType > value_type triqs::det_manip::det_manip< FunctionType >::try_remove2 (size_t i0, size_t i1, size_t j0, size_t j1) [inline]
Double Removal operation of cols j0,j1 and rows i0,i1
Returns the ratio of det Minv_new / det Minv. This routine does NOT make any modification. It has to be completed with complete_operation().
The documentation for this class was generated from the following file:
/home/parcolle/triqs/src/triqs/triqs/det_manip/det_manip.hpp