var dir_58392f70c7725409995cce3a5177e78c =
[
    [ "auto_corr_time.cpp", "auto__corr__time_8cpp_source.html", null ],
    [ "auto_corr_time.hpp", "auto__corr__time_8hpp_source.html", null ],
    [ "average_k.cpp", "average__k_8cpp_source.html", null ],
    [ "average_k.hpp", "average__k_8hpp_source.html", null ],
    [ "average_sign.cpp", "average__sign_8cpp_source.html", null ],
    [ "average_sign.hpp", "average__sign_8hpp_source.html", null ],
    [ "chi2_tau.hpp", "chi2__tau_8hpp_source.html", null ],
    [ "chi2_tau_impl.hpp", "chi2__tau__impl_8hpp_source.html", null ],
    [ "chiAB_tau.cpp", "chiAB__tau_8cpp_source.html", null ],
    [ "chiAB_tau.hpp", "chiAB__tau_8hpp_source.html", null ],
    [ "density.cpp", "density_8cpp_source.html", null ],
    [ "density.hpp", "density_8hpp_source.html", null ],
    [ "histogram.cpp", "histogram_8cpp_source.html", null ],
    [ "histogram.hpp", "histogram_8hpp_source.html", null ],
    [ "M3ph_iw.cpp", "M3ph__iw_8cpp_source.html", null ],
    [ "M3ph_iw.hpp", "M3ph__iw_8hpp_source.html", null ],
    [ "M3ph_tau.cpp", "M3ph__tau_8cpp_source.html", null ],
    [ "M3ph_tau.hpp", "M3ph__tau_8hpp_source.html", null ],
    [ "M3pp_iw.cpp", "M3pp__iw_8cpp_source.html", null ],
    [ "M3pp_iw.hpp", "M3pp__iw_8hpp_source.html", null ],
    [ "M3pp_tau.cpp", "M3pp__tau_8cpp_source.html", null ],
    [ "M3pp_tau.hpp", "M3pp__tau_8hpp_source.html", null ],
    [ "M3xph_tau.cpp", "M3xph__tau_8cpp_source.html", null ],
    [ "M3xph_tau.hpp", "M3xph__tau_8hpp_source.html", null ],
    [ "M4_iw.cpp", "M4__iw_8cpp_source.html", null ],
    [ "M4_iw.hpp", "M4__iw_8hpp_source.html", null ],
    [ "M4ph_iw.cpp", "M4ph__iw_8cpp_source.html", null ],
    [ "M4ph_iw.hpp", "M4ph__iw_8hpp_source.html", null ],
    [ "M4pp_iw.cpp", "M4pp__iw_8cpp_source.html", null ],
    [ "M4pp_iw.hpp", "M4pp__iw_8hpp_source.html", null ],
    [ "M_iw.cpp", "M__iw_8cpp_source.html", null ],
    [ "M_iw.hpp", "M__iw_8hpp_source.html", null ],
    [ "M_tau.cpp", "M__tau_8cpp_source.html", null ],
    [ "M_tau.hpp", "M__tau_8hpp_source.html", null ]
];